'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),E=require('./dist/economy.js');
const now=Date.now(),at=new Date(now).toISOString();
function fixtures(){return ['Bridgewatch','Martlock','Lymhurst','Fort Sterling','Thetford','Caerleon'].flatMap(city=>['T4_HIDE','T3_LEATHER','T4_LEATHER'].map(item_id=>({city,item_id,quality:1,sell_price_min:item_id==='T4_HIDE'?(city==='Martlock'?139:104):item_id==='T3_LEATHER'?238:350,buy_price_max:item_id==='T4_LEATHER'?340:100,sell_price_min_date:at,buy_price_max_date:at})));}
function state(){const s=E.defaults();Object.assign(s.settings,{capital:1000000,maxPct:100,reserve:0,tax:4,sellSetup:2.5,buySetup:2.5,feesConfirmed:true,profileConfirmed:true,fame:45,craftMinutes:5});s.mode='profit';for(const r of Object.values(s.routes))Object.assign(r,{minutes:20,risk:'lower',confirmed:true});return s;}
test('T4 recipe conserves materials and terminates recursively',()=>{const r=E.simulate(420,210,.367,13.5);assert.equal(r.output,329);assert.deepEqual(r.passes.map(x=>x.crafts),[210,77,28,10,3,1]);assert.equal(r.fee,329*13.5);for(const p of r.passes){assert.equal(p.usedHide,2*p.crafts);assert.equal(p.usedLeather,p.crafts);}assert.equal(r.initial.hide-r.leftovers.hide,r.consumed.hide);assert.ok(r.leftovers.hide<2||r.leftovers.leather<1);});
test('calibration discrepancy is exposed, never patched to equal observed output',()=>{const c=E.calibration;assert.equal(c.reportedOutput-c.passes.reduce((s,p)=>s+p.crafts,0),3);assert.equal(c.plannerPaid,null);assert.notEqual(E.simulate(420,210,.367,13.5).output,c.reportedOutput);});
test('station fees apply to ALL crafts, unaffected by return discount',()=>{const r=E.simulate(420,210,.367,13.5);assert.equal(r.fee,r.passes.reduce((s,p)=>s+p.fee,0));assert.ok(r.fee>210*13.5);assert.notEqual(r.fee,329*13.5*(1-.367));});
test('zero return, odd quantities and no ingredients are coherent',()=>{assert.equal(E.simulate(421,210,0,13.5).output,210);assert.equal(E.simulate(421,210,0,13.5).leftovers.hide,1);assert.equal(E.simulate(0,0,.367,null).fee,null);assert.throws(()=>E.simulate(10,5,1,13.5));});
test('weighted depth costs the complete lot correctly, including partial last level',()=>{const levels=E.parseLevels('10 @ 104\n50 @ 106\n100 @ 108\n260 @ 111');assert.equal(E.fill(levels,420).cost,46000);assert.equal(E.fill(levels,20).cost,2100);assert.equal(E.fill(levels,421).cost,null);assert.equal(E.fill([{price:100,quantity:5},{price:120,quantity:5}],6,'sell').cost,700);});
test('unknown depth remains an estimate; stale manual depth stays stale',()=>{const q=E.quote(fixtures(),[],'T4_HIDE','Lymhurst','buy',420,60,now);assert.equal(q.total,43680);assert.equal(q.depth,false);const old={city:'Lymhurst',item:'T4_HIDE',kind:'buy',price:104,quantity:420,at:'2020-01-01T00:00:00Z'};const o=E.quote(fixtures(),[old],'T4_HIDE','Lymhurst','buy',420,60,now);assert.equal(o.depth,true);assert.equal(o.fresh,false);});
test('manual depth insufficient for lot blocks calculation instead of pretending all units exist',()=>{const o={city:'Lymhurst',item:'T4_HIDE',kind:'buy',price:104,quantity:10,at};const q=E.quote(fixtures(),[o],'T4_HIDE','Lymhurst','buy',420,60,now);assert.equal(q.total,null);assert.ok(q.blockers.length);});
test('inventory reduces new cash but retains economic cost; existing output is not sold',()=>{const s=state(),x=E.evaluate(s,fixtures(),'Martlock','Martlock');assert.equal(x.needHide,414);assert.equal(x.needLeather,209);assert.equal(x.sale.total,329*340);assert.equal(x.stockValue,6*139+238);assert.equal(x.cashSurplus-x.economicProfit,x.stockValue-x.residual);});
test('inventory is local: remote stock is used only at selected origin',()=>{const s=state();s.inventory.Bridgewatch.T4_HIDE=100;assert.equal(E.evaluate(s,fixtures(),'Bridgewatch','Martlock').needHide,314);assert.equal(E.evaluate(s,fixtures(),'Lymhurst','Martlock').needHide,414);});
test('physical source route beats local when savings exceed transport',()=>{const s=state(),rows=E.compareRoutes(s,fixtures());const local=rows.find(x=>x.origin==='Martlock'),remote=rows.find(x=>x.origin==='Lymhurst');assert.equal(local.netSavings,0);assert.equal(remote.netSavings,414*35);assert.ok(remote.economicProfit>local.economicProfit);assert.equal(remote.transportPerMinute,414*35/20);});
test('Travel Planner quote of 78376 makes the cheaper remote source worse',()=>{const s=state();Object.assign(s.routes['in:Bridgewatch'],{mode:'planner',cost:78376,at});const rows=E.compareRoutes(s,fixtures());assert.ok(rows.find(x=>x.origin==='Bridgewatch').netSavings<0);});
test('unknown or expired cargo quote blocks an operation',()=>{const s=state();Object.assign(s.routes['in:Bridgewatch'],{mode:'planner',cost:null,at:null});let r=E.evaluate(s,fixtures(),'Bridgewatch','Martlock');assert.equal(r.cashRequired,null);assert.ok(r.blockers.some(x=>x.includes('coste')));s.routes['in:Bridgewatch'].cost=1;s.routes['in:Bridgewatch'].at='2020-01-01T00:00:00Z';r=E.evaluate(s,fixtures(),'Bridgewatch','Martlock');assert.ok(r.blockers.some(x=>x.includes('vencida')));});
test('unknown sales tax yields unknown net profit, not zero-tax profit',()=>{const s=state();s.settings.tax=null;const r=E.evaluate(s,fixtures(),'Martlock','Martlock');assert.equal(r.economicProfit,null);assert.ok(r.blockers.includes('Falta impuesto de venta'));});
test('unaffordable operations violate reserve and experiment limits',()=>{const s=state();Object.assign(s.settings,{capital:42909,reserve:5000,maxPct:10});const r=E.evaluate(s,fixtures(),'Martlock','Martlock');assert.equal(r.eligible,false);assert.ok(r.blockers.some(x=>x.includes('Efectivo insuficiente')));assert.ok(r.blockers.some(x=>x.includes('límite de capital')));});
test('Buy Orders never silently use highest bid as a proposed purchase price',()=>{const s=state(),r=E.evaluate(s,fixtures(),'Lymhurst','Martlock','order-instant');assert.equal(r.raw.total,null);assert.ok(r.blockers.some(x=>x.includes('objetivo')));});
test('all four execution modes apply only appropriate order fees',()=>{const s=state();for(const [item,kind,price]of [['T4_HIDE','buyOrder',104],['T3_LEATHER','buyOrder',238],['T4_LEATHER','sellOrder',350]])s.overrides.push({city:'Martlock',item,kind,price,at});const a=E.evaluate(s,fixtures(),'Martlock','Martlock','instant');assert.equal(a.buyFee,0);assert.equal(a.sellFee,0);const b=E.evaluate(s,fixtures(),'Martlock','Martlock','order-order');assert.equal(b.buyFee,b.purchases*.025);assert.equal(b.sellFee,b.sale.total*.025);assert.equal(b.profitPerHour,null);});
test('stale prices and unknown depth lower confidence; no high-confidence profit',()=>{const s=state(),r=E.evaluate(s,fixtures(),'Martlock','Martlock');assert.equal(r.confidence,'BAJA');const old=fixtures().map(x=>({...x,buy_price_max_date:'2020-01-01T00:00:00Z'}));assert.equal(E.evaluate(s,old,'Martlock','Martlock').eligible,false);});
test('training requires Fame and obeys loss cap; objective rankings differ',()=>{const s=state();s.mode='training';s.settings.fame=null;assert.ok(E.evaluate(s,fixtures(),'Martlock','Martlock').blockers.some(x=>x.includes('Fame')));s.settings.fame=45;s.settings.maxLoss=0;const bad=fixtures().map(x=>x.item_id==='T4_LEATHER'?{...x,buy_price_max:1}:x);assert.ok(E.evaluate(s,bad,'Martlock','Martlock').blockers.some(x=>x.includes('pérdida máxima')));});
test('risk exclusion and unknown travel time cannot become silent zero cost of time',()=>{const s=state();assert.ok(E.evaluate(s,fixtures(),'Caerleon','Martlock').blockers.some(x=>x.includes('riesgo')));s.settings.timeValue=100;s.routes['in:Lymhurst'].minutes=null;const r=E.evaluate(s,fixtures(),'Lymhurst','Martlock');assert.equal(r.adjustedProfit,null);assert.ok(r.blockers.some(x=>x.includes('duración')));});
test('settings reject missing required capital values and unreasonable return rates',()=>{const s=state();s.settings.capital=null;assert.throws(()=>E.validateSettings(s.settings));s.settings.capital=1000;s.settings.rrr=99;assert.throws(()=>E.validateSettings(s.settings));});
